# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7vx485tffg1157-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.cache/wt [current_project]
set_property parent.project_path C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/imports/MIN_SUM/BITS.h
set_property file_type "Verilog Header" [get_files C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/imports/MIN_SUM/BITS.h]
read_verilog -library xil_defaultlib {
  C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/imports/MIN_SUM/cnp_dc47.v
  C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/imports/MIN_SUM/connect_unit.v
  C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/new/min_gen16_1.v
  C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/imports/MIN_SUM/min_gen2.v
  C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/new/min_gen22.v
  C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/imports/MIN_SUM/min_gen4.v
  C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/new/Top.v
}
read_ip -quiet C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]
set_property is_locked true [get_files C:/Users/shane/Desktop/Practicum/Programming/Project/CNPU3/CNPU3.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Top -part xc7vx485tffg1157-1


write_checkpoint -force -noxdef Top.dcp

catch { report_utilization -file Top_utilization_synth.rpt -pb Top_utilization_synth.pb }
